### PR TITLE
Fix another _isNegative_ spec bug

### LINKED ISSUE #127: `FormatNumericToString` will errantly convert -0 to +0 then back to -0 before calling `ToRaw[Precision|Fixed]`
The `FormatNumericToString` will do the following if `x` is `negative-zero`:

```
1. If x is negative-zero, then
    a. Let isNegative be true.
    b. Set x to 0.
2. Else,
   ...
3. If isNegative, then
    a. Let x be -x.
```

So `x` will be set to `0` in step 1b, then back to `-0` in step 3a. This seems to break the assumptions of the AOs `x` is later used in, e.g. `ToRawPrecision` and `ToRawFixed` state that `x` "must be a finite non-negative mathematical value".

Should step 3 be a substep of step 2?

### PR DESCRIPTION
**Pull request by sffc**
Fixes #127

### CODE REVIEW

**Comment by anba** [comment]
The change is harmless, but not strictly required, because applying `-` on any [mathematical value](https://tc39.es/ecma262/#mathematical-value) still returns a mathematical value, even for zero.

**Comment by trflynn89** [comment]
> The change is harmless, but not strictly required, because applying `-` on any [mathematical value](https://tc39.es/ecma262/#mathematical-value) still returns a mathematical value, even for zero.

The problem is if `x` was originally `-0` when passed to `FormatNumericToString`, it would be set to `0` in step 1b, then back to `-0` in step 4a. This breaks the AOs it is then passed into which assume `x` is positive, and also makes step 14 (which flips the sign again) set `x` to positive `0`.

**Comment by anba** [comment]
There's no distinct `-0` value for mathematical values, i.e. `-0` is exactly equal to `+0`.

**Review by gibson042 — APPROVED** [review]
@anba is right.

**Pull request merged**
